CC = gcc
LD = gcc

CFLAGS = -g -std=gnu99  -Wall -Wextra 
#CFLAGS = -g -std=c99 -pedantic -Wall -Wextra -Werror -lpthread   

all: line_separator


line_separator: line_separator.c
	$(CC) $(CFLAGS) $< -o $@


